name: Build OpenWrt Passwall2 WHW03 v2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            clang \
            flex \
            bison \
            g++ \
            gawk \
            gcc-multilib \
            gettext \
            git \
            libncurses5-dev \
            libssl-dev \
            python3-setuptools \
            rsync \
            unzip \
            wget


      - name: Download OpenWrt
        run: |
          git clone --depth=1 --branch openwrt-24.10 https://github.com/openwrt/openwrt.git


      - name: Add Passwall2
        run: |
          cd openwrt

          git config --global http.version HTTP/1.1

          git clone --depth=1 https://github.com/xiaorouji/openwrt-passwall.git package/passwall

          git clone --depth=1 https://github.com/xiaorouji/openwrt-passwall-packages.git package/passwall-packages

          ./scripts/feeds update -a
          ./scripts/feeds install -a


      - name: Configure OpenWrt
        run: |
          cd openwrt

          echo "CONFIG_TARGET_ipq40xx=y" > .config
          echo "CONFIG_TARGET_ipq40xx_generic=y" >> .config
          echo "CONFIG_TARGET_DEVICE_ipq40xx_generic_DEVICE_linksys_whw03=y" >> .config

          echo "CONFIG_PACKAGE_luci=y" >> .config
          echo "CONFIG_PACKAGE_luci-ssl=y" >> .config

          echo "CONFIG_PACKAGE_luci-app-passwall2=y" >> .config

          echo "CONFIG_PACKAGE_xray-core=y" >> .config
          echo "CONFIG_PACKAGE_sing-box=y" >> .config
          echo "CONFIG_PACKAGE_tcping=y" >> .config

          echo "CONFIG_PACKAGE_kmod-usb-storage=y" >> .config
          echo "CONFIG_PACKAGE_block-mount=y" >> .config
          echo "CONFIG_PACKAGE_kmod-fs-ext4=y" >> .config

          echo "CONFIG_PACKAGE_curl=y" >> .config
          echo "CONFIG_PACKAGE_ca-certificates=y" >> .config

          make defconfig


      - name: Build firmware
        run: |
          cd openwrt

          make download -j4

          make -j$(nproc) V=s


      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt-Passwall2-WHW03-v2
          path: openwrt/bin/targets/ipq40xx/generic/
